### ISSUE TITLE
Using on Wear OS devices

### ISSUE THREAD

**Issue by alborzs** [exozet/Geolocator#10]
This is not an issue really, I am just wondering if this library can be used on **Wear OS** devices.
I am trying to use the **Geofence** but I am not getting any hit.
By the way how do you set the [LoiteringDelay](https://developers.google.com/android/reference/com/google/android/gms/location/Geofence.Builder#public-geofence.builder-setloiteringdelay-int-loiteringdelayms) for delay between GEOFENCE_TRANSITION_ENTER and GEOFENCE_TRANSITION_DWELLING? 
I am running it on a **Fossil Falster 3, Android 9, API 28**.

**Comment by kibotu** [comment]
to be honest no idea, also there is no way for me to test this :/ but feel free to fork add a pull request D:
