### ISSUE TITLE
location_min_distance_for_updates_in_meters not working as intended

### ISSUE THREAD

**Issue by IsslamElkasah** [exozet/Geolocator#11]
Hi
I have changed the xml values as follow:
`<?xml version="1.0" encoding="utf-8"?>
<resources>

    <integer name="location_update_interval_in_millis">180000</integer>
    <integer name="location_fastest_update_interval_in_millis">180000</integer>
    <integer name="location_max_wait_time_interval_in_millis">300000</integer>
    <integer name="location_min_distance_for_updates_in_meters">50</integer>

</resources>
I get a log entry every 3 minutes which is correct. But when the current location changes significantly, it should fire again but I get nothing. I'm using [this app](https://play.google.com/store/apps/details?id=com.blogspot.newapphorizons.fakegps) to fake my location on the emulator and I move my location few km away but the event keeps waiting for that time interval.
It should work on both time interval and min_distance settings, right?

EDIT:  I've noticed that the first three integer values are used here: https://github.com/exozet/Geolocator/blob/master/Geolocator/src/main/java/com/sprotte/geolocator/tracking/LocationTracker.kt
but the location_min_distance_for_updates_in_meters is not used. Could this be it? How to solve it?

Thanks very much

**Comment by kibotu** [comment]
you were correct, somehow we missed forwarding the config to the location request within the location request. resolved in version 1.3.0

https://github.com/exozet/Geolocator/blob/master/Geolocator/src/main/java/com/sprotte/geolocator/tracking/LocationTracker.kt#L83
