### ISSUE TITLE
changing update frequency at runtime

### ISSUE THREAD

**Issue by IsslamElkasah** [exozet/Geolocator#12]
Hi
Is it possible to supply the values that determines how long before we get a location update at runtime instead of using `config.xml` ?
I am trying to allow the users to specify these parameters , so it's not convenient to have them hard-coded in an xml file 

Thank you

**Comment by kibotu** [comment]
cool idea! I won't be able to add this feature atm, but as always PRs are very welcome

**Comment by AgnaldoNP** [comment]
Hi, I Created a PR to this case:
https://github.com/exozet/Geolocator/pull/13
