### ISSUE TITLE
Cannot resolve symbol Unit.INSTANCE

### ISSUE THREAD

**Issue by alexarnoldi** [exozet/Geolocator#17]
after i add dependency library i get this 
error : Cannot resolve symbol Unit .

**Comment by kibotu** [comment]
are you trying to use this library within a kotlin project?

**Comment by alexarnoldi** [comment]
No.i use it in android java project...

**Comment by kibotu** [comment]
[Unit is a kotlin object](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/), not sure how it could be missing tbh, perhaps proguard?

**Comment by kibotu** [comment]
i believe it was caused by this
```groovy
   packagingOptions {
        exclude 'META-INF/library-core_release.kotlin_module'
        exclude 'META-INF/lib_release.kotlin_module'
    }
```
which i've removed
