### ISSUE TITLE
Doesnt work if the device is in Doze Model

### ISSUE THREAD

**Issue by mudassirzulfiqar** [exozet/Geolocator#2]
There is an issue with any geofence library that it doesn't work when the device is in doze mode. If the device is in the car and person is going to office from home, then because of the doze mode state, geofence doesn't trigger.
You can also try that use case, by forcing your phone into doze mode using adb commands.

**Comment by kibotu** [comment]
are there any workarounds known?

**Comment by mudassirzulfiqar** [comment]
There is no workarounds for this, I have been solving this problem for 2 years now, applied all nasty solutions, This Android API is horrible, If geofence doesnt work in Doze mode then what is the purpose of GeoFence api. They should whitelisted geofence broadcast in Doze mode. You can even try Google keep GeoFence they dont work either in Doze mode.

**Comment by kibotu** [comment]
thanks for letting us know, at this point i don't think we can do anything about it for now
