### ISSUE TITLE
when i am try to add dependency i am getting this error

### ISSUE THREAD

**Issue by ashish07akg** [exozet/Geolocator#21]
Failed to resolve: com.sprotte:Geolocator:1.4.0
Show in Project Structure dialog
Affected Modules: app

same error we are getting in this dependency
implementation 'com.github.exozet:Geolocator:latest'

**Comment by kibotu** [comment]
https://jitpack.io/#exozet/Geolocator/2.0.0

build.gradle
```
allprojects {
    repositories {
      ...
        maven { url 'https://jitpack.io' }
    }
}
```

app/build.gradle
```
dependencies {
    implementation 'com.github.exozet:Geolocator:2.0.0'
}
```
