### ISSUE TITLE
Move to non-exozet Organization

### ISSUE THREAD

**Issue by en-jschuetze** [exozet/Geolocator#27]
Hallo @kibotu,

can you move the project to another organization? Or a public repo of yours? I changed the LICENSE accordingly at cfb8023c0e50c032eaaa4a63639d616db56f8881.

We are in the process of archiving the exozet organization.

Best regards

Jan

**Comment by kibotu** [comment]
done, i've moved the other public android repositories as well. let me know if I forgot something - cheers

**Comment by DracoBlue** [comment]
Excellent! Keep up the good work!
