### ISSUE TITLE
Difficult to get Lat Long and Address 

### ISSUE THREAD

**Issue by rajam1215** [exozet/Geolocator#3]
Hello @kibotu 

Library is very accurate but the Lat Long and Address not coming properly from Library. library give location update with that manner 

**E/LocationTrackerService: onLocationResult [Location[fused 37.422065,-122.084084 hAcc=603 et=+2h8m29s292ms vAcc=??? sAcc=??? bAcc=???]]**

Please make some **methods in lib** to fetch lat, long and address with functions **_(methods)_** 

**for example** 
_getLat();
getLong;
getAddress();_

Thanks

**Comment by kibotu** [comment]
I believe you get a [LocationResult](https://developers.google.com/android/reference/com/google/android/gms/location/LocationResult)

In your [LocationTrackerService](https://github.com/exozet/Geolocator/blob/master/app/src/main/java/com/sprotte/geolocator/demo/kotlin/LocationTrackerService.kt#L15)

the LocationResult returns you 
- an array of [Locations](https://developers.google.com/android/reference/com/google/android/gms/location/LocationResult#public-listlocation-getlocations-)

- and the user's [lastLocation](https://developers.google.com/android/reference/com/google/android/gms/location/LocationResult#public-location-getlastlocation-) as a [Location](https://developer.android.com/reference/android/location/Location.html)

here you have the user's

- latitude
- longitude
- altitude
- speed
- bearing
- etc.

**Comment by rajam1215** [comment]
> I believe you get a [LocationResult](https://developers.google.com/android/reference/com/google/android/gms/location/LocationResult)
> 
> In your [LocationTrackerService](https://github.com/exozet/Geolocator/blob/master/app/src/main/java/com/sprotte/geolocator/demo/kotlin/LocationTrackerService.kt#L15)
> 
> the LocationResult returns you
> 
> * an array of [Locations](https://developers.google.com/android/reference/com/google/android/gms/location/LocationResult#public-listlocation-getlocations-)
> * and the user's [lastLocation](https://developers.google.com/android/reference/com/google/android/gms/location/LocationResult#public-location-getlastlocation-) as a [Location](https://developer.android.com/reference/android/location/Location.html)
> 
> here you have the user's
> 
> * latitude
> * longitude
> * altitude
> * speed
> * bearing
> * etc.

Hello @kibotu 

So according to you location and last location is same thing, there is no change between the values of lastLocation and Location.

Thanks

**Comment by rajam1215** [comment]
Hello @kibotu 

**How to stop location service after start the service**

Thanks

**Comment by kibotu** [comment]
location and last location is not the same, location is an array of all locations of the user since the last update, if you have high frequency updates it's going to be very small

you can stop services via 
- Geofence#removeGeofence
- Geofence#removeAll
- LocationTracker#removeLocationUpdates

**Comment by kibotu** [comment]
i've updated the readme based on your questions, also added comments in demo to show how to retrieve data

https://github.com/exozet/Geolocator/blob/master/app/src/main/java/com/sprotte/geolocator/demo/kotlin/LocationTrackerService.kt#L18-L33
