### ISSUE TITLE
How to know Service in running stage or not

### ISSUE THREAD

**Issue by rajam1215** [exozet/Geolocator#4]
Hello @kibotu

Thanks for last answer, i want to know 

**In which way or method i know, your library service is running at background or not.**

Thanks

**Comment by kibotu** [comment]
we use the for geofencing https://developers.google.com/location-context/geofencing

and for location tracking https://developers.google.com/location-context/fused-location-provider

where you register for update events and receive said events only when there are some based on setup frequency. 

therefore the service is running only for a very short amount of time, so there is no point in knowing if it is running or not. 

the best practise would be to add/remove geofences and to register/unregister for location updates.

**Comment by kibotu** [comment]
we're open for pull requests, if you have any concrete feature requests

**Comment by rajam1215** [comment]
> we're open for pull requests, if you have any concrete feature requests

Hello @kibotu 

Thanks for reply can you please tell me, This library works or not work in Pie **Android (9.0)** and **(Android 10)** or **Is it work in more then of greater version of OREO** ?

_Means is it work greater then **OREO** version or not ?_ 

Thanks

**Comment by kibotu** [comment]
yes it works up to Android Q (API 29)

which essentially is the main reason to abstract google libraries for our projects, since it seems to change every year to some degree

**Comment by rajam1215** [comment]
> yes it works up to Android Q (API 29)
> 
> which essentially is the main reason to abstract google libraries for our projects, since it seems to change every year to some degree

Hello @kibotu 

_Thanks for reply, But there is one mobile device is here with i got issue may be the list is big._

_**MI POCO F1 (In this device Geo location tracking not WORK or NOT BEHAVE PROPERLY).**_

**Locations not come in given intervals**. _**Location come after very long interval when app is running stage. not work when it is killed state.**_ **This device have Android 9 (Pie)**. Please look in to it. or there is some cases for greater version then OREO.

Thanks

**Comment by kibotu** [comment]
i don't have that device, it works perfectly fine on a pixel 3 with android q though, also tested and works on samsung s8 with oreo

**Comment by kibotu** [comment]
there are limits though, for instance the update interval is not guaranteed to be super fast, it tries to but there are some conditions, e.g. flight mode where it is difficult at the least. 

for geofencing, there are also limits [<= 100 fences](https://developer.android.com/training/location/geofencing)

**Comment by rajam1215** [comment]
> i don't have that device, it works perfectly fine on a pixel 3 with android q though, also tested and works on samsung s8 with oreo

Hello @kibotu 

It works fine in reputed companies phone brand like **Google, Samsung** etc, but it is have some restriction with chines brands like **OPPO, VIVO, MI**.

with these brands devices,  library did not behave properly. **_these brands have very great battery optimization restriction_**. need to find some solution.

Thanks

**Comment by kibotu** [comment]
i see, not sure what we can do about it then :/ it sounds like they kill services faster or have lower frequency rates for background task executions

**Comment by rajam1215** [comment]
Hello @kibotu 

But if is there some issue, need to solve, you can check at your side with that kind of device, if you don't have that devices, need to create with emulator **_(Genymotion)_**.

Thanks

**Comment by rajam1215** [comment]
> i see, not sure what we can do about it then :/ it sounds like they kill services faster or have lower frequency rates for background task executions

Hello @kibotu 

Need to do auto start permission for these kind of devices, I r&d on that, please do this stuff in your library, with this thing you can solve this issue and made this awesome.

please help from this library.
https://github.com/judemanutd/AutoStarter

Thanks
