### ISSUE TITLE
[Feature] Set Expiration and Lointering delay on Geofence

### ISSUE THREAD

**Issue by galadril** [exozet/Geolocator#6]
Would be cool to also set the expiration duration, and loitering delay on the Geofence object.

_For example:_
```
.setExpirationDuration(Geofence.NEVER_EXPIRE)
.setLoiteringDelay(3000)
```

**Comment by kibotu** [comment]
i've added this here

https://github.com/exozet/Geolocator/blob/master/Geolocator/src/main/java/com/sprotte/geolocator/geofencer/GeofenceRepository.kt#L95-L97

and can be configured like this: https://github.com/exozet/Geolocator#configuration
