### ISSUE TITLE
LOCATION ACCURACY

### ISSUE THREAD

**Issue by Kreateyou** [exozet/Geolocator#8]
How to you configure for use of GPS and other Location strategies such as

>  criteria.setPowerRequirement(Criteria.POWER_LOW); // Chose your desired power consumption level.
>     criteria.setAccuracy(Criteria.ACCURACY_FINE);

**Comment by kibotu** [comment]
not supported atm, however we're open for pull requests

**Comment by kibotu** [comment]
auto close because of staleness
